- hosts: localhost
  connection: local
  become: yes
  gather_facts: false
  vars_files:
    - conf.yml
  tasks:
    - name: Install python2
      raw: sudo apt-get update
      raw: sudo apt-get install -y python-simplejson

    - name: Install deve packages
      apt: name={{ item }} update_cache=yes
      with_items: "{{ docker.packages }}"

    - name: Add official docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Repogitory
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        filename: 'docker'

    - name: Install Docker
      apt: name=docker-ce={{ docker.version }} update_cache=yes

    - name: Add User in Docker group
      shell: gpasswd -a {{ docker.user }} docker
